### ISSUE TITLE
Website down, possible cause

### ISSUE THREAD

**Issue by stevecheckoway** [openingtree/openingtree#359]
Hi,

I'm not sure if you're still maintaining openingtree but as I'm sure you know, the website is currently down.

I tested the development server by running `yarn start` and got this error.

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/steve/openingtree/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/steve/openingtree/scripts/start.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/steve/openingtree/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/steve/openingtree/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/steve/openingtree/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/steve/openingtree/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.19.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm unsure if this error is related to the website being down. But if so, this error comes from using OpenSSL with (now) unsupported algorithms or keysizes. Here's some [information](https://builtin.com/software-engineering-perspectives/err-ossl-evp-unsupported).

As a quick workaround, one can start the development server with
```bash
$ NODE_OPTIONS=--openssl-legacy-provider yarn start
```

Better would be to investigate where the unsupported algorithms/key sizes are being used and change those. I haven't looked into that yet.

**Comment by stevecheckoway** [comment]
Looks like website issues have been resolved.

**Comment by stevecheckoway** [comment]
I just tested loading openingtree.com and it worked so I closed the issue, but immediately afterward, it gave an error from cloudflare. I must have still had it in cache the first time. I've reopened the issue.
